---
- hosts: localhost
  tasks:

  - name: Install GPS Server
    apt:
      pkg:
          - gpsd
          - gpsd-clients
      state: present
      update_cache: no

  - name: copy gpsd configuration
    copy:
      src: "files/gpsd"
      dest: /etc/default/gpsd
      mode: 0644
      owner: root
      group: root

  - name: Create gpsd group
    group:
      name: "gpsd"
      state: "present"

  - name: Add mepuser to gpsd group
    user:
      name: "mepuser"
      groups: "gpsd"
      append: true

  - name: Enable gpsd.service
    systemd:
      name: gpsd.service
      masked: false
      enabled: true
    notify:
      - Restart gpsd.service

  - name: Create systemd config directory for gpsd.socket
    file:
      path: /etc/systemd/system/gpsd.socket.d
      state: directory
      mode: '0755'

  - name: Make gpsd.socket world-writable
    copy:
      dest: /etc/systemd/system/gpsd.socket.d/override.conf
      mode: '0644'
      content: |
        [Socket]
        SocketMode=0666
    notify:
      - Restart gpsd.socket

  - name: Remove ttybus and afe_serial systemd services
    file:
      path: '{{ item }}'
      state: absent
    loop:
      - /opt/ttybus
      - /etc/systemd/system/afe_serial_attach.service
      - /etc/systemd/system/afe_serial_GNSS1_control.service
      - /etc/systemd/system/afe_serial_GNSS1_gpsd.service
      - /etc/systemd/system/afe_serial_ttybus.service
      - /etc/systemd/system/afe_serial.target

  - name: Configure chrony
    blockinfile:
      path: /etc/chrony/chrony.conf
      state: present
      block: |
        manual
        makestep 1 -1
        refclock SHM 0 refid GNSS poll 1 precision 1e-1 offset 0.25 delay 0.2 noselect
        refclock SHM 1 refid PPS lock GNSS poll 3 precision 1e-7
        allow 192.168.0.0/16
    notify:
      - Restart chrony

  handlers:

  - name: Restart chrony
    systemd:
      name: chrony
      state: restarted

  - name: Restart gpsd.service
    systemd:
      name: gpsd.service
      state: restarted

  - name: Restart gpsd.socket
    systemd:
      daemon_reload: true
      name: gpsd.socket
      state: restarted
