---
- hosts: localhost
  tasks:

  - name: Install GPS Server
    apt:
      pkg:
          - gpsd
          - gpsd-clients
      state: present
      update_cache: no

  - name: copy gpsd configuration
    copy:
      src: "files/gpsd"
      dest: /etc/default/gpsd
      mode: 0644
      owner: root
      group: root

  - name: Enable gpsd.service
    systemd:
      name: gpsd
      enabled: true

  - name: Clone ttybus
    git:
      repo: https://github.com/danielinux/ttybus
      dest: /opt/ttybus
      update: no

  - name: Build ttybus
    command:
      chdir: /opt/ttybus
      cmd: make
      creates: /opt/ttybus/tty_bus

  - name: copy afe_serial target and services
    copy:
      src: "{{ item }}"
      dest: "/etc/systemd/system/"
      mode: 0644
      owner: root
      group: root
    with_fileglob:
      - "files/afe_serial/*"
    notify:
      - systemctl reload
      - start afe_serial

  - name: Configure chrony
    blockinfile:
      path: /etc/chrony/chrony.conf
      state: present
      block: |
        manual
        refclock SHM 0 refid SHM0 precision 1e-1 delay 0.2
        refclock SHM 1 refid SHM1 precision 1e-7
        #refclock PPS /dev/pps1 refid PPS precision 1e-7 offset 0.293
        allow 192.168.0.0/16
    notify:
      - Restart chrony

  handlers:

  - name: systemctl reload
    shell: /bin/systemctl daemon-reload

  - name: start afe_serial
    systemd:
      name: afe_serial.target
      state: started
      enabled: yes

  - name: Restart chrony
    systemd:
      name: chrony
      state: restarted
