---
- hosts: localhost  
  tasks:
    - name: remove /opt/icarus symlink
      file:
        path: /opt/icarus
        state: absent
      notify:
        - stop icarus daemon


  handlers:
    - name: systemctl reload
      shell: /bin/systemctl daemon-reload
        
    - name: stop icarus daemon
      systemd:
        name: icarus
        state: stopped
        enabled: false
