---
- import_playbook: ansible-pull.yml # cron job to run regularly
- import_playbook: host.yml         # misc host settings (hostname)
- import_playbook: dependencies.yml # required packages
- import_playbook: wifi.yml         # Wifi drivers & setup
- import_playbook: gpsd.yml         # Install GPS server
- import_playbook: user.yml         # user for student workshop
- import_playbook: system_services.yml  # Catch-all for non-Docker services
- import_playbook: docker.yml       # Setup Docker and pull containers
#- import_playbook: icarus.yml       # sensing platform script - now handled in Docker
- import_playbook: radioconda.yml   # GNURadio
- import_playbook: system_mem_guard.yml



# Run this last
- import_playbook: cleanup.yml
