---
- hosts: localhost
  tasks:
  - name: Check for radioconda
    stat: 
      path: /opt/radioconda/bin/gnuradio-companion
    register: radioconda

  - name: Download radioconda script
    get_url:
      url: "https://glare-sable.vercel.app/ryanvolz/radioconda/radioconda-.*-Linux-aarch64.sh"
      dest: /tmp/radioconda.sh
      mode: "0755"
      when: not gnuradio_companion.stat.exists

  - name: Run radioconda script (long)
    command: /tmp/radioconda.sh -b -f -p /opt/radioconda -m
    args:
      creates: /opt/radioconda
      when: not gnuradio_companion.stat.exists