---
- hosts: localhost
  tasks:

  - name: Create /opt/afe AFE software
    file:
      path: /opt/afe
      state: directory
      owner: mep
      group: mep
      mode: 0777

  - name: copy afe_service software
    copy:
      src: "files/afe_service.py"
      dest: "/opt/afe/afe_service.py"
      mode: 0755
      owner: mep
      group: mep

  - name: copy afe_control service
    copy:
      src: "files/afe_control.service"
      dest: "/etc/systemd/system/afe_control.service"
      mode: 0644
      owner: root
      group: root
    notify:
      - Enable afe_control

  handlers:

  - name: sEnable afe_control
    systemd:
      name: afe_control.service
      daemon_reload: yes
      state: started
      enabled: yes


