---
- hosts: localhost
  tasks:

    - name: Add mep user
      user:
        name: mep
        comment: MEP User Account
        groups: "adm, dialout, docker"
        shell: /bin/bash
        append: yes

    - name: create mep .ssh directory
      file:
        path: /home/mep/.ssh
        state: directory
        owner: mep
        group: mep
        mode: 0700

    - name: chown /opt to mep
      file:
        path: /opt/
        state: directory
        owner: root
        group: adm
        mode: 0775

    - name: copy ssh key to mep
      copy:
        src: /opt/radiohound/.ssh/mep_key
        dest: /home/mep/.ssh/id_rsa
        mode: 0600
        owner: mep
        group: mep

    - name: copy git ssh key to mep
      copy:
        src: /opt/radiohound/.ssh/id_rsa
        dest: /home/mep/.ssh/git_key
        mode: 0600
        owner: mep
        group: mep

    - name: copy authorized_keys to mep
      copy:
        src: "files/mep_authorized_keys"
        dest: /home/mep/.ssh/authorized_keys
        mode: 0600
        owner: mep
        group: mep

    - name: copy ssh config to mep
      copy:
        src: "files/mep_ssh_config"
        dest: /home/mep/.ssh/config
        mode: 0600
        owner: mep
        group: mep

    - name: Create /data for ring buffers
      file:
        path: /data
        state: directory
        owner: mep
        group: mep
        mode: 0777

    - name: Create /data/ringbuffer for incoming data
      file:
        path: /data/ringbuffer
        state: directory
        owner: mep
        group: mep
        mode: 0777

    - name: Create /data/telemetry_log for telemetry
      file:
        path: /data/telemetry_log
        state: directory
        owner: mep
        group: mep
        mode: 0777

    - name: Create /data/recordings for archive
      file:
        path: /data/recordings
        state: directory
        owner: mep
        group: mep
        mode: 0777

    - name: Add user to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%adm ALL='
        line: '%adm ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s

    - name: Make /opt/mep-examples, owned by mep user
      file:
        path: /opt/mep-examples
        state: directory
        owner: mep
        group: mep
        recurse: yes

    - name: Clone mep-examples repository
      git:
        repo: https://github.com/spectrumx/mep-examples.git
        dest: /opt/mep-examples
        update: yes
      become: yes
      become_user: mep
      ignore_errors: true
      register: git_clone_mep_examples

    - name: Install xrdp
      shell: "files/xrdp-installer-1.4.6.sh"
      become: yes
      become_user: mep
