[all]
; Hosts will be automatically added to 'all' group via Ansible run script.

; [test_group]
; test_hostname

[rfsoc]
192.168.20.100

[rfsoc:vars]
ansible_connection=ssh
ansible_host_key_checking=false
ansible_pipelining=true
ansible_private_key_file=/opt/radiohound/.ssh/mep_key
ansible_python_interpreter=/usr/bin/python
ansible_ssh_timeout=2
